export const USER_REGISTER_SUCCESS ='USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAILURE ='USER_REGISTER_FAILURE';
export const USER_LOGIN_SUCCESS ='USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE ='USER_LOGIN_FAILURE';
export const GET_MESSAGES_SUCCESS ='GET_MESSAGES_SUCCESS';
export const GET_MESSAGES_FAILURE ='GET_MESSAGES_FAILURE';
export const FETCH_CHAT_ROOMS_SUCCESS = 'FETCH_CHAT_ROOMS_SUCCESS';
export const FETCH_CHAT_ROOMS_FAILURE = 'FETCH_CHAT_ROOMS_FAILURE';